---
title: "p8105_hw2_bac2214"
author: "Brianna Carnagie"
date: "2023-10-02"
output: github_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(readxl)
```

## Problem 1
```{r}
pols_month_df = 
  read_csv("fivethirtyeight_datasets/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate_wider_delim(mon, "-", names = c("year","month","day")) |> 
  mutate(
    month = case_match(
    month,
    "01" ~ "jan",
    "02" ~ "feb",
    "03" ~ "mar",
    "04" ~ "apr",
    "05" ~ "may",
    "06" ~ "jun",
    "07" ~ "jul",
    "08" ~ "aug",
    "09" ~ "sep",
    "10" ~ "oct",
    "11" ~ "nov",
    "12" ~ "dec"), year = as.double(year)) |> 
  mutate(president = case_when(
     prez_dem == 1 ~ "dem",
    prez_gop == 1 ~ "gop",
    prez_gop == 2 ~ "gop"
  )) |> select(-prez_dem, -prez_gop, -day) 
  
 
# Second, clean the data in snp.csv using a similar process to the above. For consistency across datasets, arrange according to year and month, and organize so that year and month are the leading columns.
  
snp_df = 
  read_csv("fivethirtyeight_datasets/snp.csv") |> 
  janitor::clean_names() |> 
  separate_wider_delim(date, "/", names = c("month", "day", "year")) |> 
  select(year, month,-day, close,) |> 
  mutate(
    month = case_match(
    month,
    "1" ~ "jan",
    "2" ~ "feb",
    "3" ~ "mar",
    "4" ~ "apr",
    "5" ~ "may",
    "6" ~ "jun",
    "7" ~ "jul",
    "8" ~ "aug",
    "9" ~ "sep",
    "10" ~ "oct",
    "11" ~ "nov",
    "12" ~ "dec")) |> mutate(year = as.double(year), year = year + 2000)
  

unemployment_df = 
  read_csv("fivethirtyeight_datasets/unemployment.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(jan:dec,
               names_to = "month",
               values_to = "unemployment_percentage") 


fivethirtyeight_merge = 
  left_join(pols_month_df, snp_df) |>
  left_join(x = _, y = unemployment_df)


## about the dataset
min_year <- fivethirtyeight_merge |> 
  select(year) |> 
  pull() |> 
  min()

max_year <- fivethirtyeight_merge |> 
  select(year) |> 
  pull() |> 
  max()

num_rows = nrow(fivethirtyeight_merge)
num_col = ncol(fivethirtyeight_merge)

```

The data contains `r num_col` columns and `r num_rows`. I see that the first year of data is `r min_year`  while the most recent year is `r max_year`. The `month` and `year` variables were very important for merging the 3 datasets together. An abbreviation wasn't really necessary in this case, but it was good to keep consistent naming conventions across all 3 datasets.


